name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment selection (Allowed values = dev, qa, stg, prod)'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - stg
          - prod

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment..."

      - name: Build application
        run: |
          echo "Building application..."
          # Add your build commands here

      - name: Run tests
        run: |
          echo "Running tests..."
          # Add your test commands here

  post-build:
    needs: build
    runs-on: ubuntu-latest
    env:
      ENV_SELECTION: ${{ github.event.inputs.env }}

    steps:
      - name: Deploy to environment
        run: |
          if [[ "${{ env.ENV_SELECTION }}" == "dev" ]]; then
            echo "Deploying to dev environment..."
            # Add your dev deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "qa" ]]; then
            echo "Deploying to qa environment..."
            # Add your qa deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "stg" ]]; then
            echo "Deploying to stg environment..."
            # Add your stg deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "prod" ]]; then
            echo "Deploying to prod environment..."
            # Add your prod deployment steps here
          fi

      - name: Additional Post-Build Steps
        run: |
          echo "Performing additional post-build steps..."
          # Add any additional echo commands or actions you want to execute
