name: Run Cucumber Tests
on:
  # push:
  #   branches:
  #     - main  # Change this to match your branch name
  # pull_request:
  #   branches:
  #     - main  # Change this to match your branch name
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run Cucumber Tests
        run: mvn test -D"cucumber.filter.tags=@english and @insprint"
