name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  pre-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Set up environment
      run: echo "Setting up environment..."
    
    - name: Run pre-build tasks
      run: echo "Running pre-build tasks..."
  
  build:
    needs: pre-build
    runs-on: ubuntu-latest
    
    steps:
    - name: Build application
      run: echo "Building application..."
    
    - name: Run tests
      run: echo "Running tests..."
  
  post-build:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to environment
      run: |
        if [[ "${{ env.env_selection }}" == "dev" ]]; then
          echo "Deploying to dev environment..."
          # Add your dev deployment steps here
        elif [[ "${{ env.env_selection }}" == "qa" ]]; then
          echo "Deploying to qa environment..."
          # Add your qa deployment steps here
        elif [[ "${{ env.env_selection }}" == "stg" ]]; then
          echo "Deploying to stg environment..."
          # Add your stg deployment steps here
        elif [[ "${{ env.env_selection }}" == "prod" ]]; then
          echo "Deploying to prod environment..."
          # Add your prod deployment steps here
        fi
