name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      test-type:
        description: 'Test type selection'
        required: true
        default: 'smoke'
        options:
          - smoke
          - regression
          - unit

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Install Maven
        run: |
          sudo apt update
          sudo apt install maven -y

      - name: Build with Maven
        run: mvn clean install --batch-mode --no-transfer-progress

  post-build:
    needs: build
    runs-on: ubuntu-latest
    env:
      TEST_TYPE: ${{ github.event.inputs.test-type }}

    steps:
      - name: Deploy to environment
        run: |
          echo "Deploying the build artifacts..."

      - name: Run ${TEST_TYPE} tests
        run: |
          if [[ "${{ env.TEST_TYPE }}" == "smoke" ]]; then
            echo "Running smoke tests..."
            # Add your smoke test commands here
          elif [[ "${{ env.TEST_TYPE }}" == "regression" ]]; then
            echo "Running regression tests..."
            # Add your regression test commands here
          elif [[ "${{ env.TEST_TYPE }}" == "unit" ]]; then
            echo "Running unit tests..."
            # Add your unit test commands here
          fi
