name: CI/CD Pipeline

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment selection'
        required: true
        default: 'dev'
        options:
          - dev
          - qa
          - stg
          - prod

jobs:
  pre-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: echo "Setting up environment..."

      - name: Run pre-build tasks
        run: echo "Running pre-build tasks..."

  build:
    needs: pre-build
    runs-on: ubuntu-latest

    steps:
      - name: Build application
        run: echo "Building application..."

      - name: Run tests
        run: echo "Running tests..."

  post-build:
    needs: build
    runs-on: ubuntu-latest
    env:
      ENV_SELECTION: ${{ github.event.inputs.env }}

    steps:
      - name: Deploy to environment
        run: |
          if [[ "${{ env.ENV_SELECTION }}" == "dev" ]]; then
            echo "Deploying to dev environment..."
            # Add your dev deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "qa" ]]; then
            echo "Deploying to qa environment..."
            # Add your qa deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "stg" ]]; then
            echo "Deploying to stg environment..."
            # Add your stg deployment steps here
          elif [[ "${{ env.ENV_SELECTION }}" == "prod" ]]; then
            echo "Deploying to prod environment..."
            # Add your prod deployment steps here
          else
            echo "Invalid environment selection!"
            exit 1
          fi
